# /config/mongodb.yml
spring:
  data:
    mongodb:
      uri: mongodb://root-preprod:secret-preprod@localhost:27018/blo-sales-preprod?authSource=admin
      # Considera usar variables de entorno para credenciales en producción:
      # uri: mongodb://${MONGO_USER:sa}:${MONGO_PASS:sa}@${MONGO_HOST:localhost}:27017/${MONGO_DB:blo-sales-dev}?authSource=admin