#spring:
#  data:
#    mongodb:
#       uri: mongodb://root:secret@127.0.0.1:27017/blo-sales-dev?authSource=blo-sales-dev
spring:
  data:
    mongodb:
      uri: mongodb://root:secret@127.0.0.1:27017/blo-sales-dev?authSource=admin